config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get 'debitos/calcular'
  get 'debitos/fechar'
  get 'debitos/renovar'
  get 'debitos/checkout'

  resources :pagamentos
  resources :quarto
  resources :estadia
  resources :hospede
  resources :reserva
  resources :categoria_quarto
  
  get 'chekin', to: 'estadia#new', as: :checkin
  
  get 'chekout', to: 'debitos#checkout', as: :checkout

   root 'main#index'

end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/controllers/reserva_controller.rb
class ReservaController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reserva
  # GET /reserva.json
  def index
    @reserva = Reserva.all
  end

  # GET /reserva/1
  # GET /reserva/1.json
  def show
  end

  # GET /reserva/new
  # GET /reserva/new?numero_quarto=#
  def new
    @reserva = Reserva.new
 	if params[:numero_quarto].present?
		 @reserva.numero_quarto = params[:numero_quarto]
	end
  end

 
  # GET /reserva/1/edit
  def edit
  end

  # POST /reserva
  # POST /reserva.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserva/1
  # PATCH/PUT /reserva/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserva/1
  # DELETE /reserva/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reserva_index_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:data_inicial, :cpf, :numero_quarto, :data_final)
    end
end

app/helpers/reserva_helper.rb
module ReservaHelper
end

app/views/reserva/_form.html.erb
<%= form_for(@reserva) do |f| %>
  <% if @reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% @reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_inicial %><br>
    <%= f.date_select :data_inicial %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :numero_quarto %><br>
    <%= f.number_field :numero_quarto %>
  </div>
  <div class="field">
    <%= f.label :data_final %><br>
    <%= f.date_select :data_final %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reserva/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reserva_index_path %>

app/views/reserva/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reserva</h1>

<table>
  <thead>
    <tr>
      <th>Data inicial</th>
      <th>Cpf</th>
      <th>Numero quarto</th>
      <th>Data final</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reserva.each do |reserva| %>
      <tr>
        <td><%= reserva.data_inicial %></td>
        <td><%= reserva.cpf %></td>
        <td><%= reserva.numero_quarto %></td>
        <td><%= reserva.data_final %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reserva/new.html.erb
<h1>New Reserva</h1>

<%= render 'form' %>

<%= link_to 'Back', reserva_index_path %>

app/views/reserva/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data inicial:</strong>
  <%= @reserva.data_inicial %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @reserva.cpf %>
</p>

<p>
  <strong>Numero quarto:</strong>
  <%= @reserva.numero_quarto %>
</p>

<p>
  <strong>Data final:</strong>
  <%= @reserva.data_final %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reserva_index_path %>