config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get 'debitos/calcular'
  get 'debitos/fechar'
  get 'debitos/renovar'
  get 'debitos/checkout'

  resources :pagamentos
  resources :quarto
  resources :estadia
  resources :hospede
  resources :reserva
  resources :categoria_quarto
  
  get 'chekin', to: 'estadia#new', as: :checkin
  
  get 'chekout', to: 'debitos#checkout', as: :checkout

   root 'main#index'

end

app/models/estadia.rb
class Estadia < ActiveRecord::Base
end

app/controllers/estadia_controller.rb
class EstadiaController < ApplicationController
  before_action :set_estadia, only: [:show, :edit, :update, :destroy]

  # GET /estadia
  # GET /estadia.json
  def index
    @estadia = Estadia.all
  end

  # GET /estadia/1
  # GET /estadia/1.json
  def show
  end

  # GET /estadia/new
  def new
    @estadia = Estadia.new
  end

  # GET /estadia/1/edit
  def edit
  end

  # POST /estadia
  # POST /estadia.json
  def create
	
    @estadia = Estadia.new(estadia_params)
	
 	quarto = Quarto.find_by_numero_quarto(estadia_params[:numero_quarto])
	categoria = quarto.categoria_quarto_id
	categoriaQuarto = CategoriaQuarto.find(categoria)
	valor= categoriaQuarto.valor
	@estadia.categoria_quarto_id = categoria
	@estadia.valor_diaria = valor

    respond_to do |format|
      if @estadia.save
        format.html { redirect_to @estadia, notice: 'Estadia was successfully created.' }
        format.json { render :show, status: :created, location: @estadia }
      else
        format.html { render :new }
        format.json { render json: @estadia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estadia/1
  # PATCH/PUT /estadia/1.json
  def update
    respond_to do |format|
      if @estadia.update(estadia_params)
        format.html { redirect_to @estadia, notice: 'Estadia was successfully updated.' }
        format.json { render :show, status: :ok, location: @estadia }
      else
        format.html { render :edit }
        format.json { render json: @estadia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estadia/1
  # DELETE /estadia/1.json
  def destroy
    @estadia.destroy
    respond_to do |format|
      format.html { redirect_to estadia_index_url, notice: 'Estadia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estadia
      @estadia = Estadia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estadia_params
      params.require(:estadia).permit(:cpf, :numero_quarto, :categoria_quarto_id, :data_inicial, :data_final, :qtde_pessoas, :valor_diaria)
    end
end

app/helpers/estadia_helper.rb
module EstadiaHelper
		def calcular_atual (estadia)
		if (estadia != 0)
			@pagamentos = Pagamento.where(["id_estadia = ?", estadia])
			dias_pagos = 0
			@pagamentos.each do |pagamento|
				dias_pagos = dias_pagos + pagamento.dias
			end

			@estadia = Estadia.where(["id = ?", estadia])
			if @estadia.present?
				return '0'
			end
			@categoria = CategoriaQuarto.find(@estadia.categoria_quarto_id)
			dias_devidos = (Date.today - @estadia.first.data_inicial).to_i
			saldo = (dias_devidos - dias_pagos) *  @categoria.valor
		else
			'0'
		end
	end

	def calcular_total (estadia)
		if estadia != 0
			@pagamentos = Pagamento.where(["id_estadia = ?", estadia])
		
			dias_pagos = 0
			@pagamentos.each do |pagamento|
				dias_pagos = dias_pagos + pagamento.dias
			end
			@estadia = Estadia.where(["id = ?", estadia])
			if @estadia.present?
				@categoria = CategoriaQuarto.find(@estadia.categoria_quarto_id)
				dias_devidos = (@estadia.first.data_final - @estadia.first.data_inicial).to_i
				saldo = (dias_devidos - dias_pagos) * @categoria.valor
			else
				'0'
			end
		else
			'0'
		end
	end

	def calcular (estadia)
		if (estadia != 0)
			@pagamentos = Pagamento.where(["id_estadia = ?", estadia])
			dias_pagos = 0
			@pagamentos.each do |pagamento|
				dias_pagos = dias_pagos + pagamento.dias
			end

			@estadia = Estadia.where(["id = ?", estadia])
			if @estadia.present?
				@categoria = CategoriaQuarto.find(@estadia.first.categoria_quarto_id)
				@dias_devidos = (Date.today - @estadia.first.data_inicial).to_i
				@total_dias_devidos = (@estadia.first.data_final - @estadia.first.data_inicial).to_i
				@saldo_atual = (@dias_devidos - dias_pagos) *  @categoria.valor
				@saldo_total = (@total_dias_devidos - dias_pagos) *  @categoria.valor
			end
		end
	end
end

app/views/estadia/_form.html (copy).erb
<%= form_for(@estadia) do |f| %>
  <% if @estadia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estadia.errors.count, "error") %> prohibited this estadia from being saved:</h2>

      <ul>
      <% @estadia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :numero_quarto %><br>
    <%= f.number_field :numero_quarto %>
  </div>
  <div class="field">
    <%= f.label :categoria_quarto_id %><br>
    <%= f.number_field :categoria_quarto_id %>
  </div>
  <div class="field">
    <%= f.label :data_inicial %><br>
    <%= f.date_select :data_inicial %>
  </div>
  <div class="field">
    <%= f.label :data_final %><br>
    <%= f.date_select :data_final %>
  </div>
  <div class="field">
    <%= f.label :qtde_pessoas %><br>
    <%= f.number_field :qtde_pessoas %>
  </div>
  <div class="field">
    <%= f.label :valor_diaria %><br>
    <%= f.text_field :valor_diaria %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estadia/_form.html.erb
<%= form_for(@estadia) do |f| %>
  <% if @estadia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estadia.errors.count, "error") %> prohibited this estadia from being saved:</h2>

      <ul>
      <% @estadia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :numero_quarto %><br>
    <%= f.number_field :numero_quarto %>
  </div>
  <div class="field">
    <%= f.label :data_inicial %><br>
    <%= f.date_select :data_inicial %>
  </div>
  <div class="field">
    <%= f.label :data_final %><br>
    <%= f.date_select :data_final %>
  </div>
  <div class="field">
    <%= f.label :qtde_pessoas %><br>
    <%= f.number_field :qtde_pessoas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estadia/edit.html.erb
<h1>Editing Estadia</h1>

<%= render 'form' %>

<%= link_to 'Show', @estadia %> |
<%= link_to 'Back', estadia_index_path %>

app/views/estadia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estadia</h1>

<table>
  <thead>
    <tr>
      <th>Cpf</th>
      <th>Numero quarto</th>
      <th>Categoria quarto</th>
      <th>Data inicial</th>
      <th>Data final</th>
      <th>Qtde pessoas</th>
      <th>Valor diaria</th>
      <th>Saldo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estadia.each do |estadia| %>
		<% calcular(estadia.id) %>
      <tr>
        <td><%= estadia.cpf %></td>
        <td><%= estadia.numero_quarto %></td>
        <td><%= estadia.categoria_quarto_id %></td>
        <td><%= estadia.data_inicial %></td>
        <td><%= estadia.data_final %></td>
        <td><%= estadia.qtde_pessoas %></td>
        <td>R$ <%= estadia.valor_diaria %></td>
		<td>R$ <%if @saldo_total.present? %><%= @saldo_total %><% end %></td>
        <td><%= link_to 'Show', estadia %></td>
        <td><%= link_to 'Edit', edit_estadia_path(estadia) %></td>
        <td><%= link_to 'Destroy', estadia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estadia', new_estadia_path %>

app/views/estadia/new.html.erb
<h1>New Estadia</h1>

<%= render 'form' %>

<%= link_to 'Back', estadia_index_path %>

app/views/estadia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpf:</strong>
  <%= @estadia.cpf %>
</p>

<p>
  <strong>Numero quarto:</strong>
  <%= @estadia.numero_quarto %>
</p>

<p>
  <strong>Categoria quarto:</strong>
  <%= @estadia.categoria_quarto_id %>
</p>

<p>
  <strong>Data inicial:</strong>
  <%= @estadia.data_inicial %>
</p>

<p>
  <strong>Data final:</strong>
  <%= @estadia.data_final %>
</p>

<p>
  <strong>Qtde pessoas:</strong>
  <%= @estadia.qtde_pessoas %>
</p>

<p>
  <strong>Valor diaria:</strong>
  <%= @estadia.valor_diaria %>
</p>

<%= link_to 'Edit', edit_estadia_path(@estadia) %> |
<%= link_to 'Back', estadia_index_path %>