config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get 'debitos/calcular'
  get 'debitos/fechar'
  get 'debitos/renovar'
  get 'debitos/checkout'

  resources :pagamentos
  resources :quarto
  resources :estadia
  resources :hospede
  resources :reserva
  resources :categoria_quarto
  
  get 'chekin', to: 'estadia#new', as: :checkin
  
  get 'chekout', to: 'debitos#checkout', as: :checkout

   root 'main#index'

end

app/models/categoria_quarto.rb
class CategoriaQuarto < ActiveRecord::Base
end

app/controllers/categoria_quarto_controller.rb
class CategoriaQuartoController < ApplicationController
  before_action :set_categoria_quarto, only: [:show, :edit, :update, :destroy]

  # GET /categoria_quarto
  # GET /categoria_quarto.json
  def index
    @categoria_quarto = CategoriaQuarto.all
  end

  # GET /categoria_quarto/1
  # GET /categoria_quarto/1.json
  def show
  end

  # GET /categoria_quarto/new
  def new
    @categoria_quarto = CategoriaQuarto.new
  end

  # GET /categoria_quarto/1/edit
  def edit
  end

  # POST /categoria_quarto
  # POST /categoria_quarto.json
  def create
    @categoria_quarto = CategoriaQuarto.new(categoria_quarto_params)

    respond_to do |format|
      if @categoria_quarto.save
        format.html { redirect_to @categoria_quarto, notice: 'Categoria quarto was successfully created.' }
        format.json { render :show, status: :created, location: @categoria_quarto }
      else
        format.html { render :new }
        format.json { render json: @categoria_quarto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria_quarto/1
  # PATCH/PUT /categoria_quarto/1.json
  def update
    respond_to do |format|
      if @categoria_quarto.update(categoria_quarto_params)
        format.html { redirect_to @categoria_quarto, notice: 'Categoria quarto was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria_quarto }
      else
        format.html { render :edit }
        format.json { render json: @categoria_quarto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_quarto/1
  # DELETE /categoria_quarto/1.json
  def destroy
    @categoria_quarto.destroy
    respond_to do |format|
      format.html { redirect_to categoria_quarto_index_url, notice: 'Categoria quarto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria_quarto
      @categoria_quarto = CategoriaQuarto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_quarto_params
      params.require(:categoria_quarto).permit(:descricao, :valor)
    end
end

app/helpers/categoria_quarto_helper.rb
module CategoriaQuartoHelper
end

app/views/categoria_quarto/_form.html.erb
<%= form_for(@categoria_quarto) do |f| %>
  <% if @categoria_quarto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria_quarto.errors.count, "error") %> prohibited this categoria_quarto from being saved:</h2>

      <ul>
      <% @categoria_quarto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria_quarto/edit.html.erb
<h1>Editing Categoria Quarto</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria_quarto %> |
<%= link_to 'Back', categoria_quarto_index_path %>

app/views/categoria_quarto/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categoria Quarto</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria_quarto.each do |categoria_quarto| %>
      <tr>
        <td><%= categoria_quarto.descricao %></td>
        <td><%= categoria_quarto.valor %></td>
        <td><%= link_to 'Show', categoria_quarto %></td>
        <td><%= link_to 'Edit', edit_categoria_quarto_path(categoria_quarto) %></td>
        <td><%= link_to 'Destroy', categoria_quarto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoria quarto', new_categoria_quarto_path %>

app/views/categoria_quarto/new.html.erb
<h1>New Categoria Quarto</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_quarto_index_path %>

app/views/categoria_quarto/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @categoria_quarto.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @categoria_quarto.valor %>
</p>

<%= link_to 'Edit', edit_categoria_quarto_path(@categoria_quarto) %> |
<%= link_to 'Back', categoria_quarto_index_path %>