config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get 'debitos/calcular'
  get 'debitos/fechar'
  get 'debitos/renovar'
  get 'debitos/checkout'

  resources :pagamentos
  resources :quarto
  resources :estadia
  resources :hospede
  resources :reserva
  resources :categoria_quarto
  
  get 'chekin', to: 'estadia#new', as: :checkin
  
  get 'chekout', to: 'debitos#checkout', as: :checkout

   root 'main#index'

end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base

	def quitar (estadia)
		@pagamento = Pagamento.where(["id_estadia = ?", estadia]).first
	end
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /pagamentos
  # GET /pagamentos.json
  def index
	@pagamentos = Pagamento.all
  end

  # GET /pagamentos/1
  # GET /pagamentos/1.json
  def show
  end


  # GET /pagamentos/new
  # GET /pagamentos/new?id_estadia=#
  def new
	@pagamento = Pagamento.new
	if params[:id_estadia].present?
		@pagamento.id_estadia = params[:id_estadia]
	end
  end

  # GET /pagamentos/1/edit
  def edit
  end

  # POST /pagamentos
  # POST /pagamentos.json
  def create
	@pagamento = Pagamento.new(pagamento_params)

	respond_to do |format|
	  if @pagamento.save
		format.html { redirect_to '/debitos/calcular?id_estadia=' + @pagamento.id_estadia.to_s, notice: 'Pagamento realizado com sucesso.' }
		#format.html { redirect_to @pagamento, notice: 'Pagamento was successfully created.' }
		format.json { render :show, status: :created, location: @pagamento }
	  else
		format.html { render :new }
		format.json { render json: @pagamento.errors, status: :unprocessable_entity }
	  end
	end
  end

  # PATCH/PUT /pagamentos/1
  # PATCH/PUT /pagamentos/1.json
  def update
	respond_to do |format|
	  if @pagamento.update(pagamento_params)
		format.html { redirect_to @pagamento, notice: 'Pagamento was successfully updated.' }
		format.json { render :show, status: :ok, location: @pagamento }
	  else
		format.html { render :edit }
		format.json { render json: @pagamento.errors, status: :unprocessable_entity }
	  end
	end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.json
  def destroy
	@pagamento.destroy
	respond_to do |format|
	  format.html { redirect_to pagamentos_url, notice: 'Pagamento was successfully destroyed.' }
	  format.json { head :no_content }
	end
  end

  private
	# Use callbacks to share common setup or constraints between actions.
	def set_pagamento
	  @pagamento = Pagamento.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def pagamento_params
	  params.require(:pagamento).permit(:data, :dias, :id_estadia)
	end
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
	def calcular_atual (estadia)
		if (estadia != 0)
			@pagamentos = Pagamento.where(["id_estadia = ?", estadia])
			dias_pagos = 0
			@pagamentos.each do |pagamento|
				dias_pagos = dias_pagos + pagamento.dias
			end

			@estadia = Estadia.where(["id = ?", estadia])
			if @estadia.present?
				return '0'
			end
			@categoria = CategoriaQuarto.find(@estadia.categoria_quarto_id)
			dias_devidos = (Date.today - @estadia.first.data_inicial).to_i
			saldo = (dias_devidos - dias_pagos) *  @categoria.valor
		else
			'0'
		end
	end

	def calcular_total (estadia)
		if estadia != 0
			@pagamentos = Pagamento.where(["id_estadia = ?", estadia])
		
			dias_pagos = 0
			@pagamentos.each do |pagamento|
				dias_pagos = dias_pagos + pagamento.dias
			end
			@estadia = Estadia.where(["id = ?", estadia])
			if @estadia.present?
				@categoria = CategoriaQuarto.find(@estadia.categoria_quarto_id)
				dias_devidos = (@estadia.first.data_final - @estadia.first.data_inicial).to_i
				saldo = (dias_devidos - dias_pagos) * @categoria.valor
			else
				'0'
			end
		else
			'0'
		end
	end

	def calcular (estadia)
		if (estadia != 0)
			@pagamentos = Pagamento.where(["id_estadia = ?", estadia])
			dias_pagos = 0
			@pagamentos.each do |pagamento|
				dias_pagos = dias_pagos + pagamento.dias
			end

			@estadia = Estadia.where(["id = ?", estadia])
			if @estadia.present?
				@categoria = CategoriaQuarto.find(@estadia.first.categoria_quarto_id)
				@dias_devidos = (Date.today - @estadia.first.data_inicial).to_i
				@total_dias_devidos = (@estadia.first.data_final - @estadia.first.data_inicial).to_i
				@saldo_atual = (@dias_devidos - dias_pagos) *  @categoria.valor
				@saldo_total = (@total_dias_devidos - dias_pagos) *  @categoria.valor
			end
		end
	end



end

app/views/pagamentos/_form.html.erb
<%= form_for(@pagamento) do |f| %>
  <% if @pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagamento.errors.count, "error") %> prohibited this pagamento from being saved:</h2>

      <ul>
      <% @pagamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :dias %><br>
    <%= f.number_field :dias %>
  </div>
  <div class="field">
    <%= f.label :id_estadia %><br>
    <%= f.number_field :id_estadia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pagamentos/edit.html.erb
<h1>Editing Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagamento %> |
<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pagamentos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Dias</th>
      <th>Id estadia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pagamentos.each do |pagamento| %>
      <tr>
        <td><%= pagamento.data %></td>
        <td><%= pagamento.dias %></td>
        <td><%= pagamento.id_estadia %></td>
        <td><%= link_to 'Show', pagamento %></td>
        <td><%= link_to 'Edit', edit_pagamento_path(pagamento) %></td>
        <td><%= pagamento.quitar(1) %></td>
        <td><%= link_to 'Destroy', pagamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pagamento', new_pagamento_path %>

app/views/pagamentos/new.html.erb
<h1>New Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @pagamento.data %>
</p>

<p>
  <strong>Dias:</strong>
  <%= @pagamento.dias %>
</p>

<p>
  <strong>Id estadia:</strong>
  <%= @pagamento.id_estadia %>
</p>

<%= link_to 'Edit', edit_pagamento_path(@pagamento) %> |
<%= link_to 'Back', pagamentos_path %>